[build]
  command = "npm run build"  # Compile TypeScript files
  functions = "netlify/functions"  # The folder for serverless functions

[dev]
  command = "npm run dev"  # For local development
  port = 8080  # Your local dev port
